2019-12-16 12:14:50 WARN  ConnectionUtil:25 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for jdbc:postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:23)
	at com.revature.repositories.UserDAOImpl.addUser(UserDAOImpl.java:55)
	at com.revature.services.UserService.addUser(UserService.java:18)
	at com.revature.BankApp.findUser(BankApp.java:31)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:9)
2019-12-16 12:18:52 WARN  ConnectionUtil:25 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.util.ConnectionUtil.getConnection(ConnectionUtil.java:23)
	at com.revature.repositories.UserDAOImpl.addUser(UserDAOImpl.java:55)
	at com.revature.services.UserService.addUser(UserService.java:18)
	at com.revature.BankApp.findUser(BankApp.java:31)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:9)
2019-12-16 12:38:54 WARN  UserDAOImpl:72 - Unable to add user
org.postgresql.util.PSQLException: ERROR: relation "users" does not exist
  Position: 13
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.UserDAOImpl.addUser(UserDAOImpl.java:68)
	at com.revature.services.UserService.addUser(UserService.java:18)
	at com.revature.BankApp.findUser(BankApp.java:31)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:9)
2019-12-17 08:59:11 WARN  UserDAOImpl:161 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: column "fname" does not exist
  Position: 36
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserByFnameAndPassword(UserDAOImpl.java:146)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:33)
	at com.revature.BankApp.findUserInDB(BankApp.java:221)
	at com.revature.BankApp.findUser(BankApp.java:34)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:10)
2019-12-17 09:04:41 WARN  UserDAOImpl:161 - Unable to retrieve the user by using first name and password
org.postgresql.util.PSQLException: ERROR: column "password" does not exist
  Position: 56
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserByFnameAndPassword(UserDAOImpl.java:146)
	at com.revature.services.UserService.getUserByFnameAndPassword(UserService.java:33)
	at com.revature.BankApp.findUserInDB(BankApp.java:221)
	at com.revature.BankApp.findUser(BankApp.java:34)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:10)
2019-12-17 10:10:24 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "accounts" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:12:53 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "accounts" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:14:36 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "accounts" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:17:50 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:21:57 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:23:55 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 10:42:28 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 11:07:02 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 11:17:34 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 11:22:36 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 11:36:43 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 11:39:43 WARN  UserDAOImpl:196 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 12:04:22 WARN  UserDAOImpl:197 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 12:07:12 WARN  UserDAOImpl:197 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 12:35:19 WARN  UserDAOImpl:197 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 12:47:28 WARN  UserDAOImpl:197 - Unable to retrieve user's account
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.UserDAOImpl.getUserBankAccount(UserDAOImpl.java:180)
	at com.revature.services.UserService.getUserBankAccount(UserService.java:39)
	at com.revature.BankApp.deposit(BankApp.java:158)
	at com.revature.BankApp.logIn(BankApp.java:70)
	at com.revature.BankApp.findUser(BankApp.java:37)
	at com.revature.BankApp.start(BankApp.java:19)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 15:17:41 WARN  BankAccountDAOImpl:198 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.BankAccountDAOImpl.getAccountsOfUser(BankAccountDAOImpl.java:180)
	at com.revature.services.BankAccountService.getAccountsOfUser(BankAccountService.java:50)
	at com.revature.BankApp.displayAccounts(BankApp.java:344)
	at com.revature.BankApp.deposit(BankApp.java:167)
	at com.revature.BankApp.logIn(BankApp.java:71)
	at com.revature.BankApp.findUser(BankApp.java:38)
	at com.revature.BankApp.start(BankApp.java:20)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 15:19:37 WARN  BankAccountDAOImpl:198 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.BankAccountDAOImpl.getAccountsOfUser(BankAccountDAOImpl.java:180)
	at com.revature.services.BankAccountService.getAccountsOfUser(BankAccountService.java:50)
	at com.revature.BankApp.displayAccounts(BankApp.java:344)
	at com.revature.BankApp.deposit(BankApp.java:167)
	at com.revature.BankApp.logIn(BankApp.java:71)
	at com.revature.BankApp.findUser(BankApp.java:38)
	at com.revature.BankApp.start(BankApp.java:20)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 15:21:00 WARN  BankAccountDAOImpl:198 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.BankAccountDAOImpl.getAccountsOfUser(BankAccountDAOImpl.java:180)
	at com.revature.services.BankAccountService.getAccountsOfUser(BankAccountService.java:50)
	at com.revature.BankApp.displayAccounts(BankApp.java:344)
	at com.revature.BankApp.deposit(BankApp.java:167)
	at com.revature.BankApp.logIn(BankApp.java:71)
	at com.revature.BankApp.findUser(BankApp.java:38)
	at com.revature.BankApp.start(BankApp.java:20)
	at com.revature.Driver.main(Driver.java:8)
2019-12-17 15:22:22 WARN  BankAccountDAOImpl:198 - Unable to retrieve all users
org.postgresql.util.PSQLException: ERROR: relation "bankaccount" does not exist
  Position: 15
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:108)
	at com.revature.repositories.BankAccountDAOImpl.getAccountsOfUser(BankAccountDAOImpl.java:180)
	at com.revature.services.BankAccountService.getAccountsOfUser(BankAccountService.java:50)
	at com.revature.BankApp.displayAccounts(BankApp.java:344)
	at com.revature.BankApp.deposit(BankApp.java:167)
	at com.revature.BankApp.logIn(BankApp.java:71)
	at com.revature.BankApp.findUser(BankApp.java:38)
	at com.revature.BankApp.start(BankApp.java:20)
	at com.revature.Driver.main(Driver.java:8)
2019-12-18 13:05:31 WARN  BankAccountDAOImpl:158 - Unable to update the account balance
org.postgresql.util.PSQLException: No value specified for parameter 6.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.BankAccountDAOImpl.updateBalanceOfAccount(BankAccountDAOImpl.java:154)
	at com.revature.services.BankAccountService.updateBalanceOfAccount(BankAccountService.java:31)
	at com.revature.BankApp.deposit(BankApp.java:228)
	at com.revature.BankApp.logIn(BankApp.java:107)
	at com.revature.BankApp.findUser(BankApp.java:39)
	at com.revature.BankApp.start(BankApp.java:20)
	at com.revature.Driver.main(Driver.java:8)
2019-12-18 13:10:55 WARN  BankAccountDAOImpl:160 - Unable to update the account balance
org.postgresql.util.PSQLException: No value specified for parameter 7.
	at org.postgresql.core.v3.SimpleParameterList.checkAllParametersSet(SimpleParameterList.java:264)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:294)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:147)
	at com.revature.repositories.BankAccountDAOImpl.updateBalanceOfAccount(BankAccountDAOImpl.java:156)
	at com.revature.services.BankAccountService.updateBalanceOfAccount(BankAccountService.java:31)
	at com.revature.BankApp.deposit(BankApp.java:228)
	at com.revature.BankApp.logIn(BankApp.java:107)
	at com.revature.BankApp.findUser(BankApp.java:39)
	at com.revature.BankApp.start(BankApp.java:20)
	at com.revature.Driver.main(Driver.java:8)
